added help message

diff --git a/banner b/banner
--- a/banner
+++ b/banner
@@ -4,7 +4,7 @@
 # Description:   display a banner
 # Author:        Amr Elsayyad <amrelsayyad96@outlook.com>
 # Date:          2022-09-10
-# Version:       1.0.1
+# Version:       0.0.1
 
 # Exit codes
 # ==========
@@ -39,6 +39,19 @@ trap on_ctrl_c SIGINT
 
 # >>>>>>>>>>>>>>>>>>>>>>>> functions >>>>>>>>>>>>>>>>>>>>>>>>
 
+function show_help () {
+    echo "
+Usage: ${0} [OPTION]... MESSAGE
+Displays a banner with given message, color and decorator.
+
+OPTIONS:
+    -c, --color        Text color.
+    -d, --decorator    Decorator around message.
+    -h, --help         Show this help message.
+    -m, --message      Message to be displayed.
+"
+}
+
 # Usage: bannerColor "message" "color" "decorator"
 function bannerColor() {
     case ${2} in
@@ -58,7 +71,7 @@ function bannerColor() {
         ;;
         white) color=7
         ;;
-        *) echo "Error: color is not valid." 1>&2; exit 4
+        *) echo "ERROR: color is not valid." 1>&2; exit 4
         ;;
     esac
 
@@ -90,15 +103,11 @@ POSITIONAL=()
 while (( $# > 0 )); do
     case "${1}" in
         -c|--color)
-        # check if argument is after a positional argument
-        if (( ${#POSITIONAL[@]} > 0 )); then
-            echo "argument '${POSITIONAL[@]}' not understood." 1>&2
-            exit 3
-        fi
         # get switch arguments
         numOfArgs=1 # number of switch arguments
         if (( $# < numOfArgs + 1 )); then
             echo "missing argument for '${1}' option" 1>&2
+            show_help
             exit 2
         else
             color=${2}
@@ -106,31 +115,27 @@ while (( $# > 0 )); do
         fi
         ;;
         -d|--decorator)
-        # check if argument is after a positional argument
-        if (( ${#POSITIONAL[@]} > 0 )); then
-            echo "argument '${POSITIONAL[@]}' not understood." 1>&2
-            exit 3
-        fi
         # get switch arguments
         numOfArgs=1 # number of switch arguments
         if (( $# < numOfArgs + 1 )); then
             echo "missing argument for '${1}' option" 1>&2
+            show_help
             exit 2
         else
             decorator=${2}
             shift $((numOfArgs + 1)) # shift 'numOfArgs + 1' to bypass switch and its value
         fi
         ;;
+        -h|--help)
+        show_help
+        exit 0
+        ;;
         -m|--message)
-        # check if argument is after a positional argument
-        if (( ${#POSITIONAL[@]} > 0 )); then
-            echo "argument '${POSITIONAL[@]}' not understood." 1>&2
-            exit 3
-        fi
         # get switch arguments
         numOfArgs=1 # number of switch arguments
         if (( $# < numOfArgs + 1 )); then
             echo "missing argument for '${1}' option" 1>&2
+            show_help
             exit 2
         else
             message=${2}
@@ -139,7 +144,8 @@ while (( $# > 0 )); do
         ;;
         *) # unknown flag/switch
         if [[ "${1}" =~ ^- ]]; then
-            echo "argument ${1} not understood." 1>&2
+            echo "ERROR: argument '${1}' is not understood." 1>&2
+            show_help
             exit 3
         else
             POSITIONAL+=("${1}")
@@ -160,23 +166,25 @@ set -- "${POSITIONAL[@]}" # restore positional params
 if (( ${#POSITIONAL[@]} > 0 )); then
     if [ "${message}" ]; then
         # if there are both a positional arg and a message arg
-        echo "argument '${POSITIONAL[@]}' not understood." 1>&2
+        echo "ERROR: argument '${POSITIONAL[@]}' not understood." 1>&2
+        show_help
         exit 3
     elif (( ${#POSITIONAL[@]} > 1 )); then
         # if more than 1 positional arg
-        echo "argument '${POSITIONAL[@]:1}' not understood." 1>&2
+        echo "ERROR: argument '${POSITIONAL[@]:1}' not understood." 1>&2
+        show_help
         exit 3
-    else
-        # if the positional arg is the message
-        message=${POSITIONAL[0]}
     fi
+    # if the positional arg is the message
+    message=${POSITIONAL[0]}
 fi
 
 # check for existence of message
 if [ "${message}" ]; then
     bannerColor "${message}" "${color}" "${decorator}"
 else    
-    echo "No message to display!" 1>&2
+    echo "ERROR: missing argument 'MESSAGE'" 1>&2
+    show_help
 fi
 
 # <<<<<<<<<<<<<<<<<<<<<<<< rest of code <<<<<<<<<<<<<<<<<<<<<<<<
diff --git a/factorial b/factorial
--- a/factorial
+++ b/factorial
@@ -4,14 +4,14 @@
 # Description:   calculate factorial of a number
 # Author:        Amr Elsayyad <amrelsayyad96@outlook.com>
 # Date:          2022-09-08
-# Version:       1.0.0
+# Version:       0.0.1
 
 # Exit codes
 # ==========
 # 0   no error
 # 1   script interrupted
 # 2   missing argument
-# 3   unknown argument
+# 3   invalid argument
 
 
 # >>>>>>>>>>>>>>>>>>>>>>>> handler functions >>>>>>>>>>>>>>>>>>>>>>>>
@@ -38,6 +38,13 @@ trap on_ctrl_c SIGINT
 
 # >>>>>>>>>>>>>>>>>>>>>>>> functions >>>>>>>>>>>>>>>>>>>>>>>>
 
+function show_help () {
+    echo "
+Usage: ${0} [-h] NUMBER
+Get the factorial of a number.
+" # help message
+}
+
 # Usage: factorial n
 factorial ()
 {
@@ -51,6 +58,46 @@ factorial ()
 # <<<<<<<<<<<<<<<<<<<<<<<< functions <<<<<<<<<<<<<<<<<<<<<<<<
 
 
+# >>>>>>>>>>>>>>>>>>>>>>>> argument parsing >>>>>>>>>>>>>>>>>>>>>>>>
+
+POSITIONAL=()
+while (( $# > 0 )); do
+    case "${1}" in
+        -f|--flag)
+        echo flag: "${1}"
+        shift # shift once since flags have no values
+        ;;
+        -h|--help)
+        show_help
+        exit 0
+        ;;
+        -s|--switch)
+        numOfArgs=1 # number of switch arguments
+        if (( $# < numOfArgs + 1 )); then
+            shift $#
+        else
+            echo "switch: ${1} with value: ${2}"
+            shift $((numOfArgs + 1)) # shift 'numOfArgs + 1' to bypass switch and its value
+        fi
+        ;;
+        *) # unknown flag/switch
+        if [[ "${1}" =~ ^- ]]; then
+            echo "ERROR: argument '${1}' is not understood." 1>&2
+            show_help
+            exit 3
+        else
+            POSITIONAL+=("${1}")
+            shift
+        fi
+        ;;
+    esac
+done
+
+set -- "${POSITIONAL[@]}" # restore positional params
+
+# <<<<<<<<<<<<<<<<<<<<<<<< argument parsing <<<<<<<<<<<<<<<<<<<<<<<<
+
+
 # >>>>>>>>>>>>>>>>>>>>>>>> rest of code >>>>>>>>>>>>>>>>>>>>>>>>
 
 if (($# == 1)); then
@@ -59,9 +106,11 @@ if (($# == 1)); then
     echo "${result[@]}"
 elif (($# == 0)); then
     echo "Please enter number to get its factorial!"
+    show_help
     exit 2
 else
-    echo "Error parsing arguments!"
+    echo "ERROR parsing arguments!"
+    show_help
     exit 3
 fi
 
diff --git a/greet b/greet
--- a/greet
+++ b/greet
@@ -4,7 +4,7 @@
 # Description:   a shell script to greet someone
 # Author:        Amr Elsayyad <amrelsayyad96@outlook.com>
 # Date:          2022-09-10
-# Version:       1.0.1
+# Version:       0.0.1
 
 # Exit codes
 # ==========
@@ -36,6 +36,23 @@ trap on_ctrl_c SIGINT
 # <<<<<<<<<<<<<<<<<<<<<<<< event handlers <<<<<<<<<<<<<<<<<<<<<<<<
 
 
+# >>>>>>>>>>>>>>>>>>>>>>>> functions >>>>>>>>>>>>>>>>>>>>>>>>
+
+function show_help () {
+    echo "
+Usage: ${0} [OPTION]...
+Displays a greeting message for a user.
+
+OPTIONS:
+    -h, --help      Show this help message.
+    -m, --morning   Toggle morning instead of evening.
+    -n, --name      User name. Default: current user
+" # help message
+}
+
+# <<<<<<<<<<<<<<<<<<<<<<<< functions <<<<<<<<<<<<<<<<<<<<<<<<
+
+
 # >>>>>>>>>>>>>>>>>>>>>>>> argument parsing >>>>>>>>>>>>>>>>>>>>>>>>
 
 # default value for time of day
@@ -45,10 +62,15 @@ time='evening'
 POSITIONAL=()
 while (( $# > 0 )); do
     case "${1}" in
+        -h|--help)
+        show_help
+        exit 0
+        ;;
         -m|--morning)
         # check if argument is after a positional argument
         if (( ${#POSITIONAL[@]} > 0 )); then
-            echo "argument '${POSITIONAL[@]}' not understood." 1>&2
+            echo "ERROR: argument '${POSITIONAL[@]}' not understood." 1>&2
+            show_help
             exit 3
         fi
         # get switch arguments
@@ -58,13 +80,15 @@ while (( $# > 0 )); do
         -n|--name)
         # check if argument is after a positional argument
         if (( ${#POSITIONAL[@]} > 0 )); then
-            echo "argument '${POSITIONAL[@]}' not understood." 1>&2
+            echo "ERROR: argument '${POSITIONAL[@]}' not understood." 1>&2
+            show_help
             exit 3
         fi
         # get switch arguments
         numOfArgs=1 # number of switch arguments
         if (( $# < numOfArgs + 1 )); then
-            echo "missing argument for '${1}' option" >&2
+            echo "ERROR: missing argument for '${1}' option" >&2
+            show_help
             exit 2
         else
             name=${2}
@@ -73,7 +97,8 @@ while (( $# > 0 )); do
         ;;
         *) # unknown flag/switch
         if [[ "${1}" =~ ^- ]]; then
-            echo "argument ${1} not understood."
+            echo "ERROR: argument '${1}' is not understood."
+            show_help
             exit 3
         else
             POSITIONAL+=("${1}")
@@ -95,10 +120,12 @@ if (( ${#POSITIONAL[@]} > 0 )); then
     if [ "${name}" ]; then
         # if there are both a positional arg and a name arg
         echo "argument '${POSITIONAL[@]}' not understood." 1>&2
+        show_help
         exit 3
     elif (( ${#POSITIONAL[@]} > 1 )); then
         # if more than 1 positional arg
         echo "argument '${POSITIONAL[@]:1}' not understood." 1>&2
+        show_help
         exit 3
     else
         # if the positional arg is the name
diff --git a/options b/options
--- a/options
+++ b/options
@@ -4,12 +4,14 @@
 # Description:   print hello world with color selected from options menu
 # Author:        Amr Elsayyad <amrelsayyad96@outlook.com>
 # Date:          2022-09-10
-# Version:       1.0.2
+# Version:       0.0.1
 
 # Exit codes
 # ==========
 # 0   no error
 # 1   script interrupted
+# 2   missing argument
+# 3   invalid argument
 
 
 # >>>>>>>>>>>>>>>>>>>>>>>> handler functions >>>>>>>>>>>>>>>>>>>>>>>>
@@ -32,6 +34,18 @@ function on_ctrl_c() {
 trap on_ctrl_c SIGINT
 
 # <<<<<<<<<<<<<<<<<<<<<<<< event handlers <<<<<<<<<<<<<<<<<<<<<<<<
+
+
+# >>>>>>>>>>>>>>>>>>>>>>>> functions >>>>>>>>>>>>>>>>>>>>>>>>
+
+function show_help () {
+    echo "
+Usage: ${0} [-h]
+Print Hello World with color selected from options menu.
+" # help message
+}
+
+# <<<<<<<<<<<<<<<<<<<<<<<< functions <<<<<<<<<<<<<<<<<<<<<<<<
 
 
 # >>>>>>>>>>>>>>>>>>>>>>>> functions >>>>>>>>>>>>>>>>>>>>>>>>
@@ -89,6 +103,25 @@ function inputChoice() {
 }
 
 # <<<<<<<<<<<<<<<<<<<<<<<< functions <<<<<<<<<<<<<<<<<<<<<<<<
+
+
+# >>>>>>>>>>>>>>>>>>>>>>>> argument parsing >>>>>>>>>>>>>>>>>>>>>>>>
+
+while (( $# > 0 )); do
+    case "${1}" in
+        -h|--help)
+        show_help
+        exit 0
+        ;;
+        *) # unknown flag/switch
+        echo "ERROR: argument '${1}' is not understood." 1>&2
+        show_help
+        exit 3
+        ;;
+    esac
+done
+
+# <<<<<<<<<<<<<<<<<<<<<<<< argument parsing <<<<<<<<<<<<<<<<<<<<<<<<
 
 
 # >>>>>>>>>>>>>>>>>>>>>>>> rest of code >>>>>>>>>>>>>>>>>>>>>>>>
diff --git a/pacman b/pacman
--- a/pacman
+++ b/pacman
@@ -4,7 +4,7 @@
 # Description:   print a string then pacman eats it
 # Author:        Amr Elsayyad <amrelsayyad96@outlook.com>
 # Date:          2022-09-10
-# Version:       1.0.1
+# Version:       0.0.1
 
 # Exit codes
 # ==========
@@ -47,6 +47,19 @@ trap on_exit EXIT
 
 # >>>>>>>>>>>>>>>>>>>>>>>> functions >>>>>>>>>>>>>>>>>>>>>>>>
 
+function show_help () {
+    echo "
+Usage: ${0} [OPTION]... STRING
+Display given string, then pacman eats it letter by letter with given delay.
+
+OPTIONS:
+    -h, --help        Show this help message.
+    -i, --interval    Interval for pacman to wait between eating letters.
+    -p, --padding     Leftover padding after letter was eaten.
+    -s, --string      String to be displayed.
+" # help message
+}
+
 # Usage: pacMan inputString interval pad
 # Example: pacman "string" "interval" "padding"
 function pacMan () {
@@ -60,8 +73,8 @@ function pacMan () {
     local padding=""
 
     # Comment out next two lines if you are using CTRL+C event handler.
-    trap 'tput cnorm; echo' EXIT
-    trap 'exit 127' HUP INT TERM
+    # trap 'tput cnorm; echo' EXIT
+    # trap 'exit 127' HUP INT TERM
 
     tput civis # hide cursor
     tput sc # save cursor position
@@ -90,16 +103,16 @@ function pacMan () {
 POSITIONAL=()
 while (( $# > 0 )); do
     case "${1}" in
+        -h|--help)
+        show_help
+        exit 0
+        ;;
         -i|--interval)
-        # check if argument is after a positional argument
-        if (( ${#POSITIONAL[@]} > 0 )); then
-            echo "argument '${POSITIONAL[@]}' not understood." 1>&2
-            exit 3
-        fi
         # get switch arguments
         numOfArgs=1 # number of switch arguments
         if (( $# < numOfArgs + 1 )); then
-            echo "missing argument for '${1}' option" >&2
+            echo "ERROR: missing argument for '${1}' option" >&2
+            show_help
             exit 2
         else
             interval=${2}
@@ -107,15 +120,11 @@ while (( $# > 0 )); do
         fi
         ;;
         -p|--padding)
-        # check if argument is after a positional argument
-        if (( ${#POSITIONAL[@]} > 0 )); then
-            echo "argument '${POSITIONAL[@]}' not understood." 1>&2
-            exit 3
-        fi
         # get switch arguments
         numOfArgs=1 # number of switch arguments
         if (( $# < numOfArgs + 1 )); then
-            echo "missing argument for '${1}' option" >&2
+            echo "ERROR: missing argument for '${1}' option" >&2
+            show_help
             exit 2
         else
             padding=${2}
@@ -123,15 +132,11 @@ while (( $# > 0 )); do
         fi
         ;;
         -s|--string)
-        # check if argument is after a positional argument
-        if (( ${#POSITIONAL[@]} > 0 )); then
-            echo "argument '${POSITIONAL[@]}' not understood." 1>&2
-            exit 3
-        fi
         # get switch arguments
         numOfArgs=1 # number of switch arguments
         if (( $# < numOfArgs + 1 )); then
-            echo "missing argument for '${1}' option" >&2
+            echo "ERROR: missing argument for '${1}' option" >&2
+            show_help
             exit 2
         else
             string=${2}
@@ -140,7 +145,8 @@ while (( $# > 0 )); do
         ;;
         *) # unknown flag/switch
         if [[ "${1}" =~ ^- ]]; then
-            echo "argument ${1} not understood."
+            echo "ERROR: argument '${1}' is not understood."
+            show_help
             exit 3
         else
             POSITIONAL+=("${1}")
@@ -161,11 +167,13 @@ set -- "${POSITIONAL[@]}" # restore positional params
 if (( ${#POSITIONAL[@]} > 0 )); then
     if [ "${string}" ]; then
         # if there are both a positional arg and a string arg
-        echo "argument '${POSITIONAL[@]}' not understood." 1>&2
+        echo "ERROR: argument '${POSITIONAL[@]}' not understood." 1>&2
+        show_help
         exit 3
     elif (( ${#POSITIONAL[@]} > 1 )); then
         # if more than 1 positional arg
-        echo "argument '${POSITIONAL[@]:1}' not understood." 1>&2
+        echo "ERROR: argument '${POSITIONAL[@]:1}' not understood." 1>&2
+        show_help
         exit 3
     else
         # if the positional arg is the string
diff --git a/progress_bar b/progress_bar
--- a/progress_bar
+++ b/progress_bar
@@ -4,7 +4,7 @@
 # Description:   a dummy progress bar
 # Author:        Amr Elsayyad <amrelsayyad96@outlook.com>
 # Date:          2022-09-08
-# Version:       1.0.0
+# Version:       0.0.1
 
 # Exit codes
 # ==========
@@ -47,8 +47,15 @@ trap on_exit EXIT
 
 # >>>>>>>>>>>>>>>>>>>>>>>> functions >>>>>>>>>>>>>>>>>>>>>>>>
 
+function show_help () {
+    echo "
+Usage: ${0} [-h]
+Progress bar that can be implemented in any other bash script.
+" # help message
+}
+
 # Usage: progressBar "message" currentStep totalSteps
-function progressBar() {
+function progress_bar() {
     local bar='████████████████████'
     local space='....................'
     local wheel=('\' '|' '/' '-')
@@ -67,6 +74,25 @@ function progressBar() {
 # <<<<<<<<<<<<<<<<<<<<<<<< functions <<<<<<<<<<<<<<<<<<<<<<<<
 
 
+# >>>>>>>>>>>>>>>>>>>>>>>> argument parsing >>>>>>>>>>>>>>>>>>>>>>>>
+
+while (( $# > 0 )); do
+    case "${1}" in
+        -h|--help)
+        show_help
+        exit 0
+        ;;
+        *) # unknown flag/switch
+        echo "ERROR: argument '${1}' is not understood." 1>&2
+        show_help
+        exit 3
+        ;;
+    esac
+done
+
+# <<<<<<<<<<<<<<<<<<<<<<<< argument parsing <<<<<<<<<<<<<<<<<<<<<<<<
+
+
 # >>>>>>>>>>>>>>>>>>>>>>>> rest of code >>>>>>>>>>>>>>>>>>>>>>>>
 
 # Usage: progressBar "message" currentStep totalSteps
@@ -74,7 +100,7 @@ totalSteps=100
 
 for ((currentStep=1; currentStep <= totalSteps; currentStep++)); do
     sleep 0.1 # simulating one step of job
-    progressBar "Installing foo..." "${currentStep}" "${totalSteps}"
+    progress_bar "Installing foo..." "${currentStep}" "${totalSteps}"
 done
 
 echo
diff --git a/template b/template
--- a/template
+++ b/template
@@ -4,13 +4,15 @@
 # Description:   description
 # Author:        Amr Elsayyad <amrelsayyad96@outlook.com>
 # Date:          yyyy-mm-dd
-# Version:       1.0.0
+# Version:       0.0.1
 
 # Exit codes
 # ==========
 # 0   no error
 # 1   script interrupted
-# 2   error description
+# 2   missing argument
+# 3   invalid argument
+# 4   error description
 
 
 # >>>>>>>>>>>>>>>>>>>>>>>> variables >>>>>>>>>>>>>>>>>>>>>>>>
@@ -51,8 +53,15 @@ trap on_exit EXIT
 
 # >>>>>>>>>>>>>>>>>>>>>>>> functions >>>>>>>>>>>>>>>>>>>>>>>>
 
+# template function
 function name () {
     echo "$1" # arguments are accessible through $1, $2,...
+}
+
+function show_help () {
+    echo "
+Usage: ${0} [OPTION]...
+" # help message
 }
 
 # <<<<<<<<<<<<<<<<<<<<<<<< functions <<<<<<<<<<<<<<<<<<<<<<<<
@@ -67,6 +76,10 @@ while (( $# > 0 )); do
         echo flag: "${1}"
         shift # shift once since flags have no values
         ;;
+        -h|--help)
+        show_help
+        exit 0
+        ;;
         -s|--switch)
         numOfArgs=1 # number of switch arguments
         if (( $# < numOfArgs + 1 )); then
@@ -77,8 +90,14 @@ while (( $# > 0 )); do
         fi
         ;;
         *) # unknown flag/switch
-        POSITIONAL+=("${1}")
-        shift
+        if [[ "${1}" =~ ^- ]]; then
+            echo "ERROR: argument '${1}' is not understood." 1>&2
+            show_help
+            exit 3
+        else
+            POSITIONAL+=("${1}")
+            shift
+        fi
         ;;
     esac
 done
diff --git a/urldecode b/urldecode
--- a/urldecode
+++ b/urldecode
@@ -4,7 +4,7 @@
 # Description:   decodes given url
 # Author:        Amr Elsayyad <amrelsayyad96@outlook.com>
 # Date:          2022-09-08
-# Version:       1.0.1
+# Version:       0.0.1
 
 # Exit codes
 # ==========
@@ -25,13 +25,6 @@ function on_ctrl_c() {
     exit 1 # Don't remove. Use a number (1-255) for error code.
 }
 
-# Exit event handler
-function on_exit() {
-    tput cnorm # Show cursor. You need this if animation is used.
-    # i.e. clean-up code here
-    exit 0 # Exit gracefully.
-}
-
 # <<<<<<<<<<<<<<<<<<<<<<<< handler functions <<<<<<<<<<<<<<<<<<<<<<<<
 
 
@@ -40,13 +33,20 @@ function on_exit() {
 # Register CTRL+C event handler
 trap on_ctrl_c SIGINT
 
-# Register exit event handler.
-trap on_exit EXIT
-
 # <<<<<<<<<<<<<<<<<<<<<<<< event handlers <<<<<<<<<<<<<<<<<<<<<<<<
 
 
 # >>>>>>>>>>>>>>>>>>>>>>>> functions >>>>>>>>>>>>>>>>>>>>>>>>
+
+function show_help () {
+    echo "
+Usage: ${0} [-f FILE]
+Decodes given encoded URL from input stream, or given file.
+
+OPTIONS:
+    -f, --file	Input file to read encoded URLs from.
+" # help message
+}
 
 # Usage: urldecode url
 # Credit: https://unix.stackexchange.com/a/187256
@@ -65,20 +65,27 @@ while (( $# > 0 )); do
         -f|--file)
         numOfArgs=1 # number of switch arguments
         if (( $# < numOfArgs + 1 )); then
-            echo "Error: missing filepath." 1>&2
+            echo "ERROR: missing filepath." 1>&2
+            show_help
             exit 2
         else
             if [ -f "${2}" ]; then
                 urls=$(cat ${2})
             else
-                echo "Error: file does not exist."
+                echo "ERROR: file does not exist."
+                show_help
                 exit 4
             fi
             shift $((numOfArgs + 1)) # shift 'numOfArgs + 1' to bypass switch and its value
         fi
         ;;
+        -h|--help)
+        show_help
+        exit 0
+        ;;
         *) # unknown flag/switch
-        echo "Error: invalid argument." 1>&2
+        echo "ERROR: invalid argument." 1>&2
+        show_help
         exit 3
     esac
 done
diff --git a/wifi_connect b/wifi_connect
--- a/wifi_connect
+++ b/wifi_connect
@@ -4,14 +4,16 @@
 # Description:   connect to the strongest wifi signal
 # Author:        Amr Elsayyad <amrelsayyad96@outlook.com>
 # Date:          2022-09-08
-# Version:       1.0.0
+# Version:       0.0.1
 
 # Exit codes
 # ==========
 # 0   no error
 # 1   script interrupted
-# 2   failed to retrieve SSID
-# 3   failed to connect
+# 2   missing argument
+# 3   invalid argument
+# 4   failed to retrieve SSID
+# 5   failed to connect
 
 
 # >>>>>>>>>>>>>>>>>>>>>>>> handler functions >>>>>>>>>>>>>>>>>>>>>>>>
@@ -36,29 +38,56 @@ trap on_ctrl_c SIGINT
 # <<<<<<<<<<<<<<<<<<<<<<<< event handlers <<<<<<<<<<<<<<<<<<<<<<<<
 
 
+# >>>>>>>>>>>>>>>>>>>>>>>> functions >>>>>>>>>>>>>>>>>>>>>>>>
+
+function show_help () {
+    echo "Usage: wifi_connect SSID_REGEX
+Connect to the strongest wifi signal matching given pattern for SSID."
+}
+
+# <<<<<<<<<<<<<<<<<<<<<<<< functions <<<<<<<<<<<<<<<<<<<<<<<<
+
+
+# >>>>>>>>>>>>>>>>>>>>>>>> argument parsing >>>>>>>>>>>>>>>>>>>>>>>>
+
+if (( $# < 1 )); then
+    echo "ERROR: missing argument 'SSID_REGEX'." 1>&2
+    show_help
+    exit 2
+fi
+
+if (( $# > 1 )); then
+    echo "ERROR: Too many arguments." 1>&2
+    show_help
+    exit 3
+fi
+
+# <<<<<<<<<<<<<<<<<<<<<<<< argument parsing <<<<<<<<<<<<<<<<<<<<<<<<
+
+
 # >>>>>>>>>>>>>>>>>>>>>>>> rest of code >>>>>>>>>>>>>>>>>>>>>>>>
 
 # Turn on wifi
 nmcli radio wifi on 2>/dev/null
 
 # Get network SSID
-ssid=$(nmcli -f ssid dev wifi | grep 'Amol' | head -1 | xargs 2>/dev/null) # Put your regex between the quotes
+ssid=$(nmcli -f ssid dev wifi | grep -E ${1} | head -1 | xargs 2>/dev/null) # Put your regex between the quotes
 
 # Check for failure
-if [[ $? != 0 ]]; then
-    echo "Failed to retrieve network SSID."
-    exit 2
+if (( $? != 0 )); then
+    echo "ERROR: failed to retrieve network SSID." 1>&2
+    exit 4
 fi
 
 # Connect to network
-connected=$(nmcli c up $ssid 2>/dev/null)
+connected=$(nmcli c up ${ssid} 2>/dev/null)
 
 # Check for failure
-if [[ $? != 0 ]]; then
-    echo "Failed to connect to $ssid."
-    exit 3
+if (( $? != 0 )); then
+    echo "ERROR: failed to connect to ${ssid}." 1>&2
+    exit 5
 fi
 
-echo "Connected to $ssid."
+echo "Connected to ${ssid}."
 
 # <<<<<<<<<<<<<<<<<<<<<<<< rest of code <<<<<<<<<<<<<<<<<<<<<<<<
